[package]
name = "curse"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "TTY UI library"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "0.7"
cursebox = "0.1"
libc = "0.2"
